### ISSUE TITLE
Go to definition doesn't work.

### ISSUE THREAD

**Issue by alexanderbrav** [chipsalliance/verible#1668] opened 2023-02-01 11:05 UTC
A couple of questions first

 - Your IDE/editor (e.g. vscode, emacs,...) you use with verible LSP ? vscode
 - IDE version: 1-65-1
 - What other SystemVerilog plugins are active alongside ? None
-----

**What activity failed**
_(what functionality did not work as expected (e.g. Linting, Formatting, AUTO-expansion, go-to-definition, outline, hover,...)_
`Go to Definition`
**Expectation**

**What actually happened**
The `Go To Definition` function doesn't work not for module instances not for  IO ports.
**Test case**

If needed, include SystemVerilog sample file(s) that show the code you want to do an operation on
```systemverilog
module InstModule (
    o,
    i
);
  output [31:0] o;
  input i;
  wire [31:0] o = {32{i}};
endmodule

module ExampInst (
    o,
    i
);

  output o;
  input i;

  InstModule instName (  /*AUTOINST*/);

endmodule
```

**Logfiles**

If you invoke your editor with the environment variable `VERIBLE_LOGTHRESHOLD` set to 0, then useful log information will
be generated that you can include here

```bash
export VERIBLE_LOGTHRESHOLD=0
code foo.sv
```

***How to see the log output***
 - _vscode_: go to `View -> Output`, then choose `Verible Language Server` in the dropdown
 - _emacs_: there is a buffer `*verible-ls::stderr*` that contains the log output
 - _kate_: output is printed on the terminal

```txt
(paste log output here)
```

**Comment by hzeller** [comment] 2023-02-01 16:41
CC @tgorochowik

**Comment by hzeller** [comment] 2023-02-01 16:51
Alex, did you have a `verible.filelist` ? This could be #1647 (which is already fixed after the release version).
At least for the module.

The IO ports might be a separate issue. Will hand over to Grzegorz to determine.

**Comment by glatosinski** [comment] 2023-02-02 09:45
I am taking a look at it

**Comment by alexanderbrav** [comment] 2023-02-02 14:07
I didn't use `verible.filelist`.

**Comment by glatosinski** [comment] 2023-02-02 20:18
The issue is being resolved in PR #1678 - I will provide the current status there

**Comment by fangism** [comment] 2023-02-04 01:35
Acknowledging that my initial implementation (~2 years ago) did not support this style of ports.

**Closed** 2023-07-04 14:46 UTC
Labels: language-server
